-- Create hypertable that stores data in 1 day chunks
SELECT create_hypertable(
  'bybit_spot_trade',
  'time',
  chunk_time_interval => INTERVAL '1 day'
);

SELECT create_hypertable(
  'bybit_spot_orderbook',
  'time',
  chunk_time_interval => INTERVAL '1 day'
);


-- Add compression to the table
ALTER TABLE bybit_spot_trade SET (timescaledb.compress, timescaledb.compress_segmentby = 'trade_symbol');
ALTER TABLE bybit_spot_orderbook SET (timescaledb.compress, timescaledb.compress_segmentby = 'book_symbol');

SELECT add_compression_policy('bybit_spot_trade', INTERVAL '24h', '2023-06-16 09:20:00+00');
SELECT add_compression_policy('bybit_spot_orderbook', INTERVAL '24h');


-- Create index for efficient query
CREATE INDEX ix_symbol_time ON bybit_spot_trade (trade_symbol, time DESC);
CREATE INDEX ix_book_symbol_time ON bybit_spot_orderbook (book_symbol, time DESC);


-- Entity structure
CREATE TABLE bybit_spot_trade (
  time TIMESTAMPTZ NOT NULL,
  trade_id BIGINT NOT NULL,
  trade_type TEXT NOT NULL,
  trade_fill_time TIMESTAMPTZ NOT NULL,
  trade_side TEXT NOT NULL,
  trade_symbol TEXT NOT NULL,
  trade_qty REAL NOT NULL,
  trade_price REAL NOT NULL,
  trades_count SMALLINT NOT NULL,
  block_trade BOOLEAN NOT NULL,
  server TEXT NOT NULL,
  exchange TEXT NOT NULL,
  rx_time TIMESTAMPTZ NOT NULL,
  latency REAL NOT NULL
);

CREATE TABLE test_bybit_spot_trade (
  time TIMESTAMPTZ NOT NULL,
  trade_id BIGINT NOT NULL,
  trade_type TEXT NOT NULL,
  trade_fill_time TIMESTAMPTZ NOT NULL,
  trade_side TEXT NOT NULL,
  trade_symbol TEXT NOT NULL,
  trade_qty REAL NOT NULL,
  trade_price REAL NOT NULL,
  trades_count SMALLINT NOT NULL,
  block_trade BOOLEAN NOT NULL,
  server TEXT NOT NULL,
  exchange TEXT NOT NULL,
  rx_time TIMESTAMPTZ NOT NULL,
  latency REAL NOT NULL
);

CREATE TABLE bybit_spot_orderbook (
  time TIMESTAMPTZ NOT NULL,
  update_id BIGINT NOT NULL,
  seq BIGINT NOT NULL,
  ask50_price REAL NOT NULL,
  ask50_size REAL NOT NULL,
  ask49_price REAL NOT NULL,
  ask49_size REAL NOT NULL,
  ask48_price REAL NOT NULL,
  ask48_size REAL NOT NULL,
  ask47_price REAL NOT NULL,
  ask47_size REAL NOT NULL,
  ask46_price REAL NOT NULL,
  ask46_size REAL NOT NULL,
  ask45_price REAL NOT NULL,
  ask45_size REAL NOT NULL,
  ask44_price REAL NOT NULL,
  ask44_size REAL NOT NULL,
  ask43_price REAL NOT NULL,
  ask43_size REAL NOT NULL,
  ask42_price REAL NOT NULL,
  ask42_size REAL NOT NULL,
  ask41_price REAL NOT NULL,
  ask41_size REAL NOT NULL,
  ask40_price REAL NOT NULL,
  ask40_size REAL NOT NULL,
  ask39_price REAL NOT NULL,
  ask39_size REAL NOT NULL,
  ask38_price REAL NOT NULL,
  ask38_size REAL NOT NULL,
  ask37_price REAL NOT NULL,
  ask37_size REAL NOT NULL,
  ask36_price REAL NOT NULL,
  ask36_size REAL NOT NULL,
  ask35_price REAL NOT NULL,
  ask35_size REAL NOT NULL,
  ask34_price REAL NOT NULL,
  ask34_size REAL NOT NULL,
  ask33_price REAL NOT NULL,
  ask33_size REAL NOT NULL,
  ask32_price REAL NOT NULL,
  ask32_size REAL NOT NULL,
  ask31_price REAL NOT NULL,
  ask31_size REAL NOT NULL,
  ask30_price REAL NOT NULL,
  ask30_size REAL NOT NULL,
  ask29_price REAL NOT NULL,
  ask29_size REAL NOT NULL,
  ask28_price REAL NOT NULL,
  ask28_size REAL NOT NULL,
  ask27_price REAL NOT NULL,
  ask27_size REAL NOT NULL,
  ask26_price REAL NOT NULL,
  ask26_size REAL NOT NULL,
  ask25_price REAL NOT NULL,
  ask25_size REAL NOT NULL,
  ask24_price REAL NOT NULL,
  ask24_size REAL NOT NULL,
  ask23_price REAL NOT NULL,
  ask23_size REAL NOT NULL,
  ask22_price REAL NOT NULL,
  ask22_size REAL NOT NULL,
  ask21_price REAL NOT NULL,
  ask21_size REAL NOT NULL,
  ask20_price REAL NOT NULL,
  ask20_size REAL NOT NULL,
  ask19_price REAL NOT NULL,
  ask19_size REAL NOT NULL,
  ask18_price REAL NOT NULL,
  ask18_size REAL NOT NULL,
  ask17_price REAL NOT NULL,
  ask17_size REAL NOT NULL,
  ask16_price REAL NOT NULL,
  ask16_size REAL NOT NULL,
  ask15_price REAL NOT NULL,
  ask15_size REAL NOT NULL,
  ask14_price REAL NOT NULL,
  ask14_size REAL NOT NULL,
  ask13_price REAL NOT NULL,
  ask13_size REAL NOT NULL,
  ask12_price REAL NOT NULL,
  ask12_size REAL NOT NULL,
  ask11_price REAL NOT NULL,
  ask11_size REAL NOT NULL,
  ask10_price REAL NOT NULL,
  ask10_size REAL NOT NULL,
  ask09_price REAL NOT NULL,
  ask09_size REAL NOT NULL,
  ask08_price REAL NOT NULL,
  ask08_size REAL NOT NULL,
  ask07_price REAL NOT NULL,
  ask07_size REAL NOT NULL,
  ask06_price REAL NOT NULL,
  ask06_size REAL NOT NULL,
  ask05_price REAL NOT NULL,
  ask05_size REAL NOT NULL,
  ask04_price REAL NOT NULL,
  ask04_size REAL NOT NULL,
  ask03_price REAL NOT NULL,
  ask03_size REAL NOT NULL,
  ask02_price REAL NOT NULL,
  ask02_size REAL NOT NULL,
  ask01_price REAL NOT NULL,
  ask01_size REAL NOT NULL,
  bid01_price REAL NOT NULL,
  bid01_size REAL NOT NULL,
  bid02_price REAL NOT NULL,
  bid02_size REAL NOT NULL,
  bid03_price REAL NOT NULL,
  bid03_size REAL NOT NULL,
  bid04_price REAL NOT NULL,
  bid04_size REAL NOT NULL,
  bid05_price REAL NOT NULL,
  bid05_size REAL NOT NULL,
  bid06_price REAL NOT NULL,
  bid06_size REAL NOT NULL,
  bid07_price REAL NOT NULL,
  bid07_size REAL NOT NULL,
  bid08_price REAL NOT NULL,
  bid08_size REAL NOT NULL,
  bid09_price REAL NOT NULL,
  bid09_size REAL NOT NULL,
  bid10_price REAL NOT NULL,
  bid10_size REAL NOT NULL,
  bid11_price REAL NOT NULL,
  bid11_size REAL NOT NULL,
  bid12_price REAL NOT NULL,
  bid12_size REAL NOT NULL,
  bid13_price REAL NOT NULL,
  bid13_size REAL NOT NULL,
  bid14_price REAL NOT NULL,
  bid14_size REAL NOT NULL,
  bid15_price REAL NOT NULL,
  bid15_size REAL NOT NULL,
  bid16_price REAL NOT NULL,
  bid16_size REAL NOT NULL,
  bid17_price REAL NOT NULL,
  bid17_size REAL NOT NULL,
  bid18_price REAL NOT NULL,
  bid18_size REAL NOT NULL,
  bid19_price REAL NOT NULL,
  bid19_size REAL NOT NULL,
  bid20_price REAL NOT NULL,
  bid20_size REAL NOT NULL,
  bid21_price REAL NOT NULL,
  bid21_size REAL NOT NULL,
  bid22_price REAL NOT NULL,
  bid22_size REAL NOT NULL,
  bid23_price REAL NOT NULL,
  bid23_size REAL NOT NULL,
  bid24_price REAL NOT NULL,
  bid24_size REAL NOT NULL,
  bid25_price REAL NOT NULL,
  bid25_size REAL NOT NULL,
  bid26_price REAL NOT NULL,
  bid26_size REAL NOT NULL,
  bid27_price REAL NOT NULL,
  bid27_size REAL NOT NULL,
  bid28_price REAL NOT NULL,
  bid28_size REAL NOT NULL,
  bid29_price REAL NOT NULL,
  bid29_size REAL NOT NULL,
  bid30_price REAL NOT NULL,
  bid30_size REAL NOT NULL,
  bid31_price REAL NOT NULL,
  bid31_size REAL NOT NULL,
  bid32_price REAL NOT NULL,
  bid32_size REAL NOT NULL,
  bid33_price REAL NOT NULL,
  bid33_size REAL NOT NULL,
  bid34_price REAL NOT NULL,
  bid34_size REAL NOT NULL,
  bid35_price REAL NOT NULL,
  bid35_size REAL NOT NULL,
  bid36_price REAL NOT NULL,
  bid36_size REAL NOT NULL,
  bid37_price REAL NOT NULL,
  bid37_size REAL NOT NULL,
  bid38_price REAL NOT NULL,
  bid38_size REAL NOT NULL,
  bid39_price REAL NOT NULL,
  bid39_size REAL NOT NULL,
  bid40_price REAL NOT NULL,
  bid40_size REAL NOT NULL,
  bid41_price REAL NOT NULL,
  bid41_size REAL NOT NULL,
  bid42_price REAL NOT NULL,
  bid42_size REAL NOT NULL,
  bid43_price REAL NOT NULL,
  bid43_size REAL NOT NULL,
  bid44_price REAL NOT NULL,
  bid44_size REAL NOT NULL,
  bid45_price REAL NOT NULL,
  bid45_size REAL NOT NULL,
  bid46_price REAL NOT NULL,
  bid46_size REAL NOT NULL,
  bid47_price REAL NOT NULL,
  bid47_size REAL NOT NULL,
  bid48_price REAL NOT NULL,
  bid48_size REAL NOT NULL,
  bid49_price REAL NOT NULL,
  bid49_size REAL NOT NULL,
  bid50_price REAL NOT NULL,
  bid50_size REAL NOT NULL,
  book_symbol TEXT NOT NULL,
  server TEXT NOT NULL,
  exchange TEXT NOT NULL,
  rx_time TIMESTAMPTZ NOT NULL,
  latency REAL NOT NULL
);



 -- Clean table
DELETE FROM bybit_spot_trade;