const SERVER = "ubuntu-us-central";
const DB_HOST = "";
const DB_PORT = "";
const DB_USER = "";
const DB_PASSWORD = "";
const EXCHANGE = "BYBIT";
const DB_BATCH_SIZE = 5;
module.exports = {
  apps: [
    {
      name: `${EXCHANGE}_SPOT_1`,
      script: `./src/${EXCHANGE.toLowerCase()}_spot_trades.py`,
      args: ["--index", "0", "--server", SERVER],
      instances: 1,
      autorestart: true,
      max_restarts: 5,
      env_prod: {
        ENV: "production",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      env_dev: {
        ENV: "development",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      interpreter: "./venv/bin/python",
    },
    {
      name: `${EXCHANGE}_SPOT_2`,
      script: `./src/${EXCHANGE.toLowerCase()}_spot_trades.py`,
      args: ["--index", "1", "--server", SERVER],
      instances: 1,
      autorestart: true,
      max_restarts: 5,
      env_prod: {
        ENV: "production",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      env_dev: {
        ENV: "development",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      interpreter: "./venv/bin/python",
    },
    {
      name: `${EXCHANGE}_SPOT_3`,
      script: `./src/${EXCHANGE.toLowerCase()}_spot_trades.py`,
      args: ["--index", "2", "--server", SERVER],
      instances: 1,
      autorestart: true,
      max_restarts: 5,
      env_prod: {
        ENV: "production",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      env_dev: {
        ENV: "development",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      interpreter: "./venv/bin/python",
    },
    {
      name: `${EXCHANGE}_SPOT_4`,
      script: `./src/${EXCHANGE.toLowerCase()}_spot_trades.py`,
      args: ["--index", "3", "--server", SERVER],
      instances: 1,
      autorestart: true,
      max_restarts: 5,
      env_prod: {
        ENV: "production",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      env_dev: {
        ENV: "development",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      interpreter: "./venv/bin/python",
    },
    {
      name: `${EXCHANGE}_SPOT_5`,
      script: `./src/${EXCHANGE.toLowerCase()}_spot_trades.py`,
      args: ["--index", "4", "--server", SERVER],
      instances: 1,
      autorestart: true,
      max_restarts: 5,
      env_prod: {
        ENV: "production",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      env_dev: {
        ENV: "development",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      interpreter: "./venv/bin/python",
    },
    {
      name: `${EXCHANGE}_SPOT_6`,
      script: `./src/${EXCHANGE.toLowerCase()}_spot_trades.py`,
      args: ["--index", "5", "--server", SERVER],
      instances: 1,
      autorestart: true,
      max_restarts: 5,
      env_prod: {
        ENV: "production",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      env_dev: {
        ENV: "development",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      interpreter: "./venv/bin/python",
    },
    {
      name: `${EXCHANGE}_SPOT_7`,
      script: `./src/${EXCHANGE.toLowerCase()}_spot_trades.py`,
      args: ["--index", "6", "--server", SERVER],
      instances: 1,
      autorestart: true,
      max_restarts: 5,
      env_prod: {
        ENV: "production",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      env_dev: {
        ENV: "development",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      interpreter: "./venv/bin/python",
    },
    {
      name: `${EXCHANGE}_SPOT_8`,
      script: `./src/${EXCHANGE.toLowerCase()}_spot_trades.py`,
      args: ["--index", "7", "--server", SERVER],
      instances: 1,
      autorestart: true,
      max_restarts: 5,
      env_prod: {
        ENV: "production",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      env_dev: {
        ENV: "development",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      interpreter: "./venv/bin/python",
    },
    {
      name: `${EXCHANGE}_SPOT_9`,
      script: `./src/${EXCHANGE.toLowerCase()}_spot_trades.py`,
      args: ["--index", "8", "--server", SERVER],
      instances: 1,
      autorestart: true,
      max_restarts: 5,
      env_prod: {
        ENV: "production",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      env_dev: {
        ENV: "development",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      interpreter: "./venv/bin/python",
    },
    {
      name: `${EXCHANGE}_SPOT_10`,
      script: `./src/${EXCHANGE.toLowerCase()}_spot_trades.py`,
      args: ["--index", "9", "--server", SERVER],
      instances: 1,
      autorestart: true,
      max_restarts: 5,
      env_prod: {
        ENV: "production",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      env_dev: {
        ENV: "development",
        DB_HOST: DB_HOST,
        DB_PORT: DB_PORT,
        DB_USER: DB_USER,
        DB_PASSWORD: DB_PASSWORD,
        DB_BATCH_SIZE: DB_BATCH_SIZE,
      },
      interpreter: "./venv/bin/python",
    },
  ],
};
